<?php

namespace AppBundle\Repository;

/**
 * pieceJointeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PieceJointeRepository extends \Doctrine\ORM\EntityRepository
{
}
