<?php

namespace AppBundle\Repository;

/**
 * ReponseSondageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReponseSondageRepository extends \Doctrine\ORM\EntityRepository
{
}
